line-length=120
include=["ctf4science/**/*.py", "tests/**/*.py"]
exclude=["models/**", "**/*.ipynb"]

[format]
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 20

[lint]
preview = true

ignore = [
   "RET504", # it's cleaner to have assignments before returns
   "BLE001", # allow catching of blind exceptions
   "DTZ005" # Skip local timezone errors
]